"""Remove qr code url

Revision ID: c2bddba5ab5b
Revises: a59b30e31ffa
Create Date: 2025-01-22 21:10:03.334611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2bddba5ab5b'
down_revision = 'a59b30e31ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.drop_column('qr_code_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_code_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
