"""Add main_image_url to Plant model

Revision ID: d9dbbd87f8bf
Revises: 5297eda10afa
Create Date: 2025-01-22 20:01:44.679691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9dbbd87f8bf'
down_revision = '5297eda10afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_image_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('image_location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('main_image_url')

    op.drop_table('plant_images')
    # ### end Alembic commands ###
